[package]
name = "neophys"
description = "an ap physics study attempt"
license = "Unlicense"
version = "0.1.0"
edition = "2021"
authors = ["Anzle Chavez <anzlemchavez@gmail.com>"]

[lib]
name = "neophys"
path = "src/lib.rs"

[[bin]]
name = "neophys_gui"
path = "src/app.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
